name: Shell commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Say Hello
        run: echo "Hello GitHub octopus"
      - name: create a new python file
        run: |
          python3 -V
          touch new_python_file.py
          ls -l
